'use strict';
const assert = require('assert');
const { addedComments, chatRef } = require('../lib/scan');
const { evaluate, PRESETS } = require('../lib/rules');
const bal = { ...PRESETS.balanced, mode: 'balanced' };
let r = addedComments('a();\n', 'a();\n// Now uses the cache as requested\nb();\n', 'x.js');
assert.strictEqual(evaluate(r, bal).length, 1);
r = addedComments('', 'const u = "http://x"; // ok\n', 'x.js');
assert.strictEqual(r.added.length, 1);
r = addedComments('', '#!/usr/bin/env bash\necho hi # greet\n', 'x.sh');
assert.strictEqual(r.added.length, 1);
r = addedComments('', 'x = 1  # noqa: E501\n', 'x.py');
assert.strictEqual(r.added.length, 0);
r = addedComments('', "fn f<'a>(s: &'a str) -> &'a str { s } // id\n", 'x.rs');
assert.strictEqual(r.added.length, 1);
r = addedComments('', 'a()\n// one\nb()\n// two\nc()\n', 'x.ts');
assert.strictEqual(evaluate(r, bal).length, 0);
r = addedComments('', 'a()\n// one\n// two\n// three\n// four\nb()\n', 'x.ts');
assert.ok(evaluate(r, bal).length >= 4);
assert.ok(!chatRef('Retry with exponential backoff'));
assert.ok(chatRef('Changed from Vec to slice'));
assert.strictEqual(addedComments('', 'x', 'README.md'), null);
console.log('ok');
